data_root: '/home/docker/project/datasets/mvsa_s'

train_file: 'train.jsonline'
val_file: 'valid.jsonline'
test_file: 'test.jsonline'


image_res: 384
batch_size_train: 8
batch_size_test: 64 

alpha: 0.4
distill: False
warm_up: False

bert_config: 'configs/config_bert.json'
accumulation_steps: 8

optimizer: {
  opt: adamW, 
  lr: 1e-5, 
  weight_decay: 0.01
}

schedular: {
  sched: step, 
  lr: 1e-5, 
  epochs: 5,
  min_lr: 1e-6, 
  decay_rate: 0.8, 
  decay_epochs: 1,
  warmup_lr: 1e-6, 
  warmup_epochs: 1, 
  cooldown_epochs: 0
}

num_label: 5

t_pooling: 'last_max'
fuse_pooling: 'last_avg'