data_root: '/home/docker/project/datasets/mvsa_s'

train_file: 'train.json'
val_file: 'valid.json'                
test_file: 'test.json'


image_res: 384
batch_size_train: 32
batch_size_test: 64 

alpha: 0.4
distill: False
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {
  opt: adamW, 
  lr: 1e-5, 
  weight_decay: 0.03
}

schedular: {
  sched: cosine, 
  lr: 1e-5, 
  epochs: 20, 
  min_lr: 1e-6, 
  decay_rate: 1, 
  warmup_lr: 1e-5, 
  warmup_epochs: 1, 
  cooldown_epochs: 0
}

num_label: 5