data_root: '/home/docker/project/datasets/mvsa_s'

train_file: 'train_.jsonline'
val_file: 'valid_.jsonline'
test_file: 'test_.jsonline'


image_res: 384
batch_size_train: 4
batch_size_test: 64 

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert_MVSA_S.json'
accumulation_steps: 8

optimizer: {
  opt: adamW, 
  lr: 1e-5, 
  weight_decay: 0.01
}

schedular: {
  sched: step, 
  lr: 1e-5, 
  epochs: 10,
  min_lr: 1e-6, 
  decay_rate: 0.9, 
  decay_epochs: 2,
  warmup_lr: 1e-6, 
  warmup_epochs: 0, 
  cooldown_epochs: 0
}

num_label: 3

# last_avg last_max first_last_avg first_last_max cls multi
t_pooling: 'cls'
v_pooling: 'last_avg'
fuse_pooling: 'cls'
vit_depth: 12
vit_heads: 12
vit_dropout: 0.1
num_sents: 20

cnn_kernel_num: 768
cnn_kernel_size: 1

pooling_num_words: 10
pooling_num_patches: 50

bert_tokenizer: bert-base-uncased

max_image_num: 1