data_root: '/home/docker/project/datasets/mvsa_s'

train_file: 'train.json'
val_file: 'valid.json'                
test_file: 'test.json'


image_res: 384
batch_size_train: 8
batch_size_test: 64 

alpha: 0.4
distill: False
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {
  opt: adamW, 
  lr: 1e-4, 
  weight_decay: 0.01
}

schedular: {
  sched: step, 
  lr: 1e-4, 
  epochs: 20,
  min_lr: 1e-5, 
  decay_rate: 0.5, 
  decay_epochs: 1,
  warmup_lr: 1e-5, 
  warmup_epochs: 0, 
  cooldown_epochs: 0
}

num_label: 5