data_root: '/home/docker/project/datasets/yelp'

train_file: 'train.json'
val_file: 'valid.json'                
test_file: 'test.json'
# test_file: 'test/Chicago_test.json'
# test_file: 'test/Los Angeles_test.json'
# test_file: 'test/New York_test.json'
# test_file: 'test/San Francisco_test.json'
#Boston_test.json   Chicago_test.json  'Los Angeles_test.json'  'New York_test.json'  'San Francisco_test.json


image_res: 384
batch_size_train: 4
batch_size_test: 64 

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert_Yelp.json'
accumulation_steps: 8

optimizer: {
  opt: adamW, 
  lr: 1e-5, 
  weight_decay: 0.01
}

schedular: {
  sched: step, 
  lr: 1e-5, 
  epochs: 5,
  min_lr: 1e-6, 
  decay_rate: 0.9, 
  decay_epochs: 2,
  warmup_lr: 1e-6, 
  warmup_epochs: 0, 
  cooldown_epochs: 0
}

num_label: 5

# last_avg last_max first_last_avg first_last_max cls multi
t_pooling: 'first_last_avg'
v_pooling: 'last_avg'
fuse_pooling: 'first_last_avg'
vit_depth: 4
vit_heads: 12
vit_dropout: 0.5
num_sents: 1

cnn_kernel_num: 768
cnn_kernel_size: 3

pooling_num_words: 5
pooling_num_patches: 2

n_components: -1

bert_tokenizer: bert-base-uncased

max_image_num: 1
