data_root: '/home/docker/project/datasets/zol'

train_file: 'train.jsonline'
val_file: 'valid.jsonline'
test_file: 'test.jsonline'


image_res: 384
batch_size_train: 8
batch_size_test: 64 

alpha: 0.4
distill: False
warm_up: False

bert_config: 'configs/config_bert_ZOL.json'
accumulation_steps: 8

optimizer: {
  opt: adamW, 
  lr: 2e-5, 
  weight_decay: 0.01
}

schedular: {
  sched: cosine, 
  lr: 2e-5, 
  epochs: 5,
  min_lr: 1e-6, 
  decay_rate: 0.8, 
  decay_epochs: 1,
  warmup_lr: 1e-5, 
  warmup_epochs: 1, 
  cooldown_epochs: 0
}

num_label: 10
# last_avg last_max first_last_avg first_last_max cls
t_pooling: 'first_last_max'
v_pooling: 'cls'
fuse_pooling: 'cls'
vit_depth: 12
vit_heads: 12
vit_dropout: 0.0